# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 396)
        self.sort = QtWidgets.QPlainTextEdit(Form)
        self.sort.setGeometry(QtCore.QRect(110, 10, 281, 31))
        self.sort.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.sort.setObjectName("sort")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(9, 10, 81, 31))
        self.label.setObjectName("label")
        self.taste = QtWidgets.QPlainTextEdit(Form)
        self.taste.setGeometry(QtCore.QRect(110, 160, 281, 61))
        self.taste.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.taste.setObjectName("taste")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(9, 160, 81, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 81, 31))
        self.label_3.setObjectName("label_3")
        self.grains = QtWidgets.QComboBox(Form)
        self.grains.setGeometry(QtCore.QRect(110, 110, 281, 26))
        self.grains.setObjectName("grains")
        self.price = QtWidgets.QPlainTextEdit(Form)
        self.price.setGeometry(QtCore.QRect(110, 240, 281, 31))
        self.price.setObjectName("price")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 240, 81, 31))
        self.label_4.setObjectName("label_4")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(240, 340, 141, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(9, 60, 81, 16))
        self.label_5.setObjectName("label_5")
        self.roast = QtWidgets.QComboBox(Form)
        self.roast.setGeometry(QtCore.QRect(110, 60, 281, 26))
        self.roast.setObjectName("roast")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(9, 300, 81, 31))
        self.label_6.setObjectName("label_6")
        self.volume = QtWidgets.QPlainTextEdit(Form)
        self.volume.setGeometry(QtCore.QRect(110, 290, 281, 31))
        self.volume.setObjectName("volume")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Сорта кофе"))
        self.label.setText(_translate("Form", "Название сорта°"))
        self.label_2.setText(_translate("Form", "Степень обжарки"))
        self.label_3.setText(_translate("Form", "Мотолый \ в зернах"))
        self.label_4.setText(_translate("Form", "Вес упаковки"))
        self.pushButton.setText(_translate("Form", "Добавить"))
        self.label_5.setText(_translate("Form", "Описание вкуса"))
        self.label_6.setText(_translate("Form", "Цена"))
